// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251118143256_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Property<int>("Commentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Commentid"));

                    b.Property<string>("Commentby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Taskid")
                        .HasColumnType("integer");

                    b.HasKey("Commentid");

                    b.HasIndex("Commentby");

                    b.HasIndex("Taskid");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Property<int>("Projectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Projectid"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByNavigationId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Datecreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Datemodified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Projectid");

                    b.HasIndex("CreatedByNavigationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Backend.Models.ProjectTeam", b =>
                {
                    b.Property<string>("Userid")
                        .HasColumnType("text");

                    b.Property<int>("Projectid")
                        .HasColumnType("integer");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("Userid", "Projectid");

                    b.HasIndex("Projectid");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("Backend.Models.Task", b =>
                {
                    b.Property<int>("Taskid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Taskid"));

                    b.Property<string>("Assignedto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Parenttask")
                        .HasColumnType("integer");

                    b.Property<int>("Projectid")
                        .HasColumnType("integer");

                    b.Property<int>("Statusid")
                        .HasColumnType("integer");

                    b.Property<string>("Taskdescription")
                        .HasColumnType("text");

                    b.Property<string>("Taskname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Taskid");

                    b.HasIndex("Assignedto");

                    b.HasIndex("Createdby");

                    b.HasIndex("Projectid");

                    b.HasIndex("Statusid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Backend.Models.TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskStatusid"));

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("TaskStatusid");

                    b.ToTable("TaskStatuses");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("surName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.HasOne("Backend.Models.Users", "CommentbyNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("Commentby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Task", "TaskNavigation")
                        .WithMany("CommentNavigation")
                        .HasForeignKey("Taskid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentbyNavigation");

                    b.Navigation("TaskNavigation");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.HasOne("Backend.Models.Users", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedByNavigationId");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Backend.Models.ProjectTeam", b =>
                {
                    b.HasOne("Backend.Models.Project", "ProjectNavigation")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Users", "UserNavigation")
                        .WithMany("UserTeams")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Backend.Models.Task", b =>
                {
                    b.HasOne("Backend.Models.Users", "AssignedtoNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Assignedto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Users", "CreatorNavigation")
                        .WithMany("TasksNav")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Project", "ProjectNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TaskStatus", "StatusNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Statusid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Task", "ParenttaskNavigation")
                        .WithMany("InverseParenttaskNavigation")
                        .HasForeignKey("Taskid");

                    b.Navigation("AssignedtoNavigation");

                    b.Navigation("CreatorNavigation");

                    b.Navigation("ParenttaskNavigation");

                    b.Navigation("ProjectNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Navigation("ProjectTeams");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Backend.Models.Task", b =>
                {
                    b.Navigation("CommentNavigation");

                    b.Navigation("InverseParenttaskNavigation");
                });

            modelBuilder.Entity("Backend.Models.TaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tasks");

                    b.Navigation("TasksNav");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
